trigger:
- main

pool:
  name: 'Default'  # or the name of your self-hosted agent pool

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          name: 'Default'  # or the name of your self-hosted agent pool
        steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '8.x'  # Change this to your required .NET version
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '**/*.sln'  # Update this path as needed

        - task: VSBuild@1
          inputs:
            solution: '**/*.sln'  # Update this path as needed
            msbuildArgs: '-property:Configuration=$(buildConfiguration)'
            platform: 'Any CPU'
            configuration: '$(buildConfiguration)'

        - task: VSTest@2
          inputs:
            platform: 'Any CPU'
            configuration: '$(buildConfiguration)'
            
        - powershell: |
            Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip" -OutFile "$(Agent.ToolsDirectory)/chromedriver.zip"
            Expand-Archive -Path "$(Agent.ToolsDirectory)/chromedriver.zip" -DestinationPath "$(Agent.ToolsDirectory)" -Force
            Remove-Item -Path "$(Agent.ToolsDirectory)/chromedriver.zip" -Force
          displayName: 'Download and install ChromeDriver'

        # Run Selenium tests
        - powershell: |
            # Add ChromeDriver to the PATH
            $env:Path += ";$(Agent.ToolsDirectory)"
            # Run the tests
            dotnet test
          displayName: 'Run Selenium tests'

        - task: CopyFiles@2
          inputs:
            contents: '**/bin/$(buildConfiguration)/**'
            targetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        pool:
          name: 'Default'  # or the name of your self-hosted agent pool
        steps:
        - download: current
          artifact: drop

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'StudentCourseEnrollSystem'  # Replace with your service connection name
            appName: 'CourseEnroll'  # Replace with your App Service name
            package: '$(Pipeline.Workspace)/drop/**/*.zip'