trigger:
- main

pool:
  name: 'Default'  # or the name of your self-hosted agent pool

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Change this to your required .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'  # Update this path as needed

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'  # Update this path as needed
    msbuildArgs: '-property:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/2.41/chromedriver_win32.zip -OutFile chromedriver.zip
      Expand-Archive chromedriver.zip -DestinationPath $(Agent.ToolsDirectory)

- task: CmdLine@2
  inputs:
    script: 'dotnet test TestProject/UnitTest1.csproj --logger "trx;LogFileName=testresults.trx"'